DATA:
  data_root: /root/data2/data/ade2/ADEChallengeData2016  # data path
  train_list: ~/data/ADE20K/train.txt
  val_list: /root/data2/Projects/ICCV2023/NIPS2023/nips23/SPNet-master/data/ADE20K/val.txt
  classes: 150

TRAIN:
  arch: spnet
  spm_on: True
  layers: 50
  dataset: ade20k
  backbone: resnet50
  sync_bn: True  # adopt sync_bn or not
  train_h: 480
  train_w: 480
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0, 1, 2, 3]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 120
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 20
  save_freq: 1
  save_path: exp/ade20k/spnet50/model
  weight: ./pretrained/resnet50-25c4b509.pth # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: /root/data2/Projects/ICCV2023/NIPS2023/nips23/SPNet-master/data/ADE20K/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 480
  test_w: 480
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/ade20k/spnet50/model1/train_epoch_120.pth  # evaluation model path
  save_folder: exp/ade20k/spnet50/result/epoch_120/val/ss  # results save folder
  colors_path: dataset/ade20k/ade20k_colors.txt  # path of dataset colors
  names_path: dataset/ade20k/ade20k_names.txt  # path of dataset category names
